version: "3.9"  # optional since v1.27.0
services:
  node-1:
    image: julandoomar/bully-algorithm
    networks:
      - pervasive
  node-2:
    image: julandoomar/bully-algorithm
    networks:
      - pervasive
  node-3:
    image: julandoomar/bully-algorithm
    networks:
      - pervasive
  node-4:
    image: julandoomar/bully-algorithm
    networks:
      - pervasive
  node-5:
    image: julandoomar/bully-algorithm
    networks:
      - pervasive

networks:
  pervasive:
    external: true